name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout SunEngine
      uses: actions/checkout@v2
    - name: Checkout SunEngineBuild
    - uses: actions/checkout@v2
      with:
        repository: DmitrijOkeanij/SunEngineBuild
        path: SunEngineBuild
      
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Build with dotnet
      run: dotnet publish --configuration Release "Server/SunEngine.Cli" --output build/Server
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
          
    - name: npm install, install quasar, quasar build
      run: |
        cd Client
        cp -RT src/site.template src/site
        npm install
        npm -g install @quasar/cli
        npx quasar build
        cd ..
        cp -RT Client/dist/spa/. build/wwwroot
      env:
        CI: true
        
    - name: Copy Config, Resources, .SunEngineRoot dirs and file
      run: |
        cp -RT Config.template build/Config
        cp -RT Resources build/Resources
        cp -T .SunEngineRoot build/.SunEngineRoot
        
    - name: Clear build on git
      run: git rm -rf --ignore-unmatch build
      
    - name: Commit build
      uses: EndBug/add-and-commit@v2
      with:
         author_name: SunEngine GitHub Action Script
         author_email: github-action@sunengine.site
         cwd: "SunEngineBuild"
         message: "Build auto commit"
         path: "build"
         pattern: "*"
         force: true
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
