name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release "Server/SunEngine.Cli" --output "build"
    - name: Commit build
      uses: EndBug/add-and-commit@v2
      with:
         author_name: Your Name
         author_email: mail@example.com
         cwd: "."
         message: "Your commit message"
         path: "build"
         pattern: "*"
         force: true
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
    - name: Build Quasar Client
      run: cd Client && npx quasar build
